-- 103_nfe_tributos_icms_pis_cofins.sql
-- Adiciona colunas de ICMS, PIS, COFINS e ICMS-Partilha em nfe_saidas e nfe_entradas.
-- Valores preenchidos pelo ERP Bridge (SAP S4/HANA) a partir de s4i_nfe_impostos.

ALTER TABLE nfe_saidas
  ADD COLUMN IF NOT EXISTS base_icms     NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms          NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_st       NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_pis      NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_cofins   NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins        NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_partilha NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_partilha NUMERIC(15,2) DEFAULT 0;

ALTER TABLE nfe_entradas
  ADD COLUMN IF NOT EXISTS base_icms     NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms          NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_st       NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_pis      NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_cofins   NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins        NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_partilha NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_partilha NUMERIC(15,2) DEFAULT 0;
