-- 104_cte_entradas_tributos.sql
-- Adiciona colunas de ICMS, PIS, COFINS em cte_entradas.

ALTER TABLE cte_entradas
  ADD COLUMN IF NOT EXISTS base_icms     NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms          NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_st       NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_pis      NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis           NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_cofins   NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins        NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_partilha NUMERIC(15,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_partilha NUMERIC(15,2) DEFAULT 0;
